trigger: 'none'

pool:
  vmImage: ubuntu-latest

steps:

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: '61e27906-3275-4d01-8122-fa2c1a02c81e'
    pipeline: '6'
    buildVersionToDownload: 'latest'
    downloadType: 'specific'
    itemPattern: '*.nupkg'
    downloadPath: '$(System.DefaultWorkingDirectory)'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(System.DefaultWorkingDirectory)/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGet.org'